name: vote

on:
  workflow_dispatch:
    inputs:
      label-name:
        type: string
        required: true

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: show issue list
        run: gh issue list -l "${LABEL_NAME}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL_NAME: ${{ github.event.inputs.label-name }}