name: vote

on:
  workflow_dispatch:
    inputs:
      label-name:
        type: string
        required: true

jobs:
  count:
    runs-on: ubuntu-latest
    outputs:
        issues: ${{ steps.show-issue-list.outputs.issues }}
    steps:
      - name: clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: get reactions for issues
        id: show-issue-list
        run: |
            issues=$(gh issue list -l ${LABEL_NAME})
            echo $issues | grep -o -E "^[0-9]+" | while read issue_id; do
                echo $issue_id
                gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${GITHUB_REPOSITORY}/issues/${issue_id}/reactions
            done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL_NAME: ${{ github.event.inputs.label-name }}
          GITHUB_REPOSITORY: ${{ github.repository }}
